- title: Trusting Invisibility – Ethics & Design for AI
  organizer: DesignUp Asia
  location: National Design Center, SG
  date: June 18, 2019

- title: UX Thailand Conference 2018
  organizer: UXTH
  location: Siam Square, Bangkok, TH
  date: February 23, 2019

- title: New Adventures in Responsive Web Design Master Class
  organizer: PWDO
  location: The Globe Tower, Taguig, PH
  date: October 23, 2016

- title: Front-End Performance & Optimization Master Class
  organizer: PWDO
  location: Hive Hotel, Quezon City, PH
  date: October 23, 2016

- title: Form Function Class 7
  organizer: PWDO
  location: Hive Hotel, Quezon City, PH
  date: October 22, 2016

- title: UX Design and Validating Your Startup
  organizer: Melewi
  location: 47 East Coworking Space, Quezon City, PH
  date: March 18 to 19, 2016

- title: Web Animation Workshop
  organizer: PWDO
  location: Globe Labs, Makati City, PH
  date: November 21, 2015

- title: Atomic Design Master Class
  organizer: PWDO
  location: Hive Hotel, Quezon City, PH
  date: November 15, 2015

- title: Form Function Class 6
  organizer: PWDO
  location: Hive Hotel, Quezon City, PH
  date: November 14, 2015

- title: Web Design Workshop
  organizer: PWDO
  location: Globe Labs, Makati City, PH
  date: August 29, 2015
